//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace Microsoft.Practices.ServiceFactory.ServiceContracts
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class ServiceContractDslExplorer : ServiceContractDslExplorerBase
	{
		/// <summary>
		/// Constructs a new ServiceContractDslExplorer.
		/// </summary>
		public ServiceContractDslExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the ServiceContractDslExplorerToolWindow.
	/// </summary>
	internal abstract class ServiceContractDslExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new ServiceContractDslExplorerBase.
		/// </summary>
		protected ServiceContractDslExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::Microsoft.Practices.ServiceFactory.ServiceContracts.ServiceContractDslDomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.ServiceContracts.Message.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("MessageExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.ServiceContracts.Service.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ServiceExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.ServiceContracts.Operation.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OperationExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.ServiceContracts.ServiceContract.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ServiceContractExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.ServiceContracts.XsdMessage.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("XsdMessageExplorerImage")), 
							false); 
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.ServiceContractDslExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::Microsoft.Practices.ServiceFactory.ServiceContracts.ServiceContractModel.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
	}
}
	


