//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Microsoft.Practices.ServiceFactory.DataContracts.DataContractDiagram")]

namespace Microsoft.Practices.ServiceFactory.DataContracts
{
	/// <summary>
	/// Double-derived base class for DomainClass DataContractDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Microsoft.Practices.ServiceFactory.DataContracts.DataContractDiagram.DisplayName", typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslDomainModel), "Microsoft.Practices.ServiceFactory.DataContracts.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Microsoft.Practices.ServiceFactory.DataContracts.DataContractDiagram.Description", typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslDomainModel), "Microsoft.Practices.ServiceFactory.DataContracts.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("0bbd8a85-2e98-4635-8616-f27cb83caae3")]
	public abstract partial class DataContractDiagramBase : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Most connectors are mapped to element links, but there can be exceptions. This method tell if a connector should be
		/// mapped to an element link.
		/// </summary>
		public override bool IsConnectorMappedToLink(DslDiagrams::BinaryLinkShape connector)
		{
			#region Check Parameters
			global::System.Diagnostics.Debug.Assert(connector != null);
			if (connector == null)
				throw new global::System.ArgumentNullException("connector");
			#endregion
			if (connector.GetType() == typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractAggregationConnector))
				return false;
			return base.IsConnectorMappedToLink(connector);
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollection)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollectionShape newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollectionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollection)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollectionShape newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollectionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractBaseCanBeContainedOnContracts)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.AggregationConnector newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.AggregationConnector(this.Partition);
				return newShape;
			}
			if(element is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractBaseIsBeingReferenceOnDataContractCollections)
			{
				global::Microsoft.Practices.ServiceFactory.DataContracts.ReferenceConnector newShape = new global::Microsoft.Practices.ServiceFactory.DataContracts.ReferenceConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape.DecoratorsInitialized += FaultContractCompartmentShapeDecoratorMap.OnDecoratorsInitialized;
			global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape.DecoratorsInitialized += DataContractEnumCompartmentShapeDecoratorMap.OnDecoratorsInitialized;
			global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollectionShape.DecoratorsInitialized += PrimitiveDataTypeCollectionShapeDecoratorMap.OnDecoratorsInitialized;
			global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollectionShape.DecoratorsInitialized += DataContractCollectionShapeDecoratorMap.OnDecoratorsInitialized;
			global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape.DecoratorsInitialized += DataContractCompartmentShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for FaultContractCompartmentShape.
		/// </summary>
		internal static partial class FaultContractCompartmentShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for FaultContractCompartmentShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Microsoft.Practices.ServiceFactory.DataContracts.ExtensibleModelElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DataContractEnumCompartmentShape.
		/// </summary>
		internal static partial class DataContractEnumCompartmentShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DataContractEnumCompartmentShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Microsoft.Practices.ServiceFactory.DataContracts.ExtensibleModelElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for PrimitiveDataTypeCollectionShape.
		/// </summary>
		internal static partial class PrimitiveDataTypeCollectionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for PrimitiveDataTypeCollectionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Microsoft.Practices.ServiceFactory.DataContracts.ExtensibleModelElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DataContractCollectionShape.
		/// </summary>
		internal static partial class DataContractCollectionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DataContractCollectionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Microsoft.Practices.ServiceFactory.DataContracts.ExtensibleModelElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Microsoft.Practices.ServiceFactory.DataContracts.ExtensibleModelElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DataContractCompartmentShape.
		/// </summary>
		internal static partial class DataContractCompartmentShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DataContractCompartmentShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Microsoft.Practices.ServiceFactory.DataContracts.ExtensibleModelElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Sticky Toolbox Support
		private string stickyToolboxItemId = null; // Id of the last-selected sticky toolbox item.
		
		/// <summary>
		/// Called when the selection on toolbox changed (through a single-click, or pressing up/down arrow keys).
		/// Base implementation does nothing.
		/// Upon double-click, a single-click is fired first, followed by a double-click. I.e. OnToolboxSelectionChanged
		/// will be called, followed by OnToolboxitemSelected (if the selected item is not "Pointer").
		/// </summary>
		/// <param name="toolboxItem">New toolbox item with selection. This can be null, if "Pointer" mode is selected.</param>
		public override void OnToolboxSelectionChanged(DslDesign::ModelingToolboxItem toolboxItem)
		{
			base.OnToolboxSelectionChanged(toolboxItem);
		
			// When a toolbox item is single-clicked, we need to turn off the sticky mode.
			this.stickyToolboxItemId = null;
			if (this.ActiveDiagramView != null)
			{
				DslDiagrams::CreateAction createAction = this.ActiveDiagramView.ActiveMouseAction as DslDiagrams::CreateAction;
				if (createAction != null)
				{
					createAction.StickyMode = false;
				}
				else
				{
					DslDiagrams::ConnectAction connectAction = this.ActiveDiagramView.ActiveMouseAction as DslDiagrams::ConnectAction;
					if (connectAction != null)
					{
						connectAction.StickyMode = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Called on selection of a ToolboxItem. (A selection is a double-click, or pressing Enter).
		/// The selection cannot be null; this method is not called when the "Pointer" mode is selected.
		/// Upon double-click, a single-click is fired first, followed by a double-click. I.e. OnToolboxSelectionChanged
		/// will be called, followed by OnToolboxitemSelected (if the selected item is not "Pointer").
		/// </summary>
		/// <param name="toolboxItem">Selected toolbox item.</param>
		public override bool OnToolboxItemSelected(DslDesign::ModelingToolboxItem toolboxItem)
		{
			// Save the current sticky item choice.
			this.stickyToolboxItemId = toolboxItem.Id;
			
			// Return true to indicate that the toolbox selection action is handled. Otherwise the old
			// behavior of creating new element on double-click will be carried out.
			return true;
		}
		#endregion
		
		#region Toolbox actions
		private bool changingMouseAction;
		private global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractToolCreateAction dataContractToolCreateAction;
		private global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumToolCreateAction dataContractEnumToolCreateAction;
		private global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollectionToolCreateAction primitiveDataTypeCollectionToolCreateAction;
		private global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollectionToolCreateAction dataContractCollectionToolCreateAction;
		private global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractToolCreateAction faultContractToolCreateAction;
		private global::Microsoft.Practices.ServiceFactory.DataContracts.AggregationConnectionToolConnectAction aggregationConnectionToolConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				bool stickyMode = false;
				DslDesign::ModelingToolboxItem selectedToolboxItem = activeView.Toolbox.GetSelectedToolboxItem() as DslDesign::ModelingToolboxItem;
				if (selectedToolboxItem != null && selectedToolboxItem.Id == this.stickyToolboxItemId)
				{
					stickyMode = true;
				}
				else
				{
					stickyMode = false;
					this.stickyToolboxItemId = null;
				}
		
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelper.DataContractToolFilterString))
				{
					if (this.dataContractToolCreateAction == null)
					{
						this.dataContractToolCreateAction = new global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractToolCreateAction(this);
						this.dataContractToolCreateAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnToolboxActionDeactivated);
					}
					this.dataContractToolCreateAction.StickyMode = stickyMode;
					action = this.dataContractToolCreateAction;
				}
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelper.DataContractEnumToolFilterString))
				{
					if (this.dataContractEnumToolCreateAction == null)
					{
						this.dataContractEnumToolCreateAction = new global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumToolCreateAction(this);
						this.dataContractEnumToolCreateAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnToolboxActionDeactivated);
					}
					this.dataContractEnumToolCreateAction.StickyMode = stickyMode;
					action = this.dataContractEnumToolCreateAction;
				}
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelper.PrimitiveDataTypeCollectionToolFilterString))
				{
					if (this.primitiveDataTypeCollectionToolCreateAction == null)
					{
						this.primitiveDataTypeCollectionToolCreateAction = new global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollectionToolCreateAction(this);
						this.primitiveDataTypeCollectionToolCreateAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnToolboxActionDeactivated);
					}
					this.primitiveDataTypeCollectionToolCreateAction.StickyMode = stickyMode;
					action = this.primitiveDataTypeCollectionToolCreateAction;
				}
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelper.DataContractCollectionToolFilterString))
				{
					if (this.dataContractCollectionToolCreateAction == null)
					{
						this.dataContractCollectionToolCreateAction = new global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollectionToolCreateAction(this);
						this.dataContractCollectionToolCreateAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnToolboxActionDeactivated);
					}
					this.dataContractCollectionToolCreateAction.StickyMode = stickyMode;
					action = this.dataContractCollectionToolCreateAction;
				}
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelper.FaultContractToolFilterString))
				{
					if (this.faultContractToolCreateAction == null)
					{
						this.faultContractToolCreateAction = new global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractToolCreateAction(this);
						this.faultContractToolCreateAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnToolboxActionDeactivated);
					}
					this.faultContractToolCreateAction.StickyMode = stickyMode;
					action = this.faultContractToolCreateAction;
				}
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslToolboxHelper.AggregationConnectionToolFilterString))
				{
					if (this.aggregationConnectionToolConnectAction == null)
					{
						this.aggregationConnectionToolConnectAction = new global::Microsoft.Practices.ServiceFactory.DataContracts.AggregationConnectionToolConnectAction(this);
						this.aggregationConnectionToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnToolboxActionDeactivated);
					}
					this.aggregationConnectionToolConnectAction.StickyMode = stickyMode;
					action = this.aggregationConnectionToolConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom toolbox action.
		/// </summary>
		private void OnToolboxActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom toolbox action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.dataContractToolCreateAction != null)
					{
						this.dataContractToolCreateAction.Dispose();
						this.dataContractToolCreateAction = null;
					}
					if(this.dataContractEnumToolCreateAction != null)
					{
						this.dataContractEnumToolCreateAction.Dispose();
						this.dataContractEnumToolCreateAction = null;
					}
					if(this.primitiveDataTypeCollectionToolCreateAction != null)
					{
						this.primitiveDataTypeCollectionToolCreateAction.Dispose();
						this.primitiveDataTypeCollectionToolCreateAction = null;
					}
					if(this.dataContractCollectionToolCreateAction != null)
					{
						this.dataContractCollectionToolCreateAction.Dispose();
						this.dataContractCollectionToolCreateAction = null;
					}
					if(this.faultContractToolCreateAction != null)
					{
						this.faultContractToolCreateAction.Dispose();
						this.faultContractToolCreateAction = null;
					}
					if(this.aggregationConnectionToolConnectAction != null)
					{
						this.aggregationConnectionToolConnectAction.Dispose();
						this.aggregationConnectionToolConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// DataContractDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0bbd8a85, 0x2e98, 0x4635, 0x86, 0x16, 0xf2, 0x7c, 0xb8, 0x3c, 0xaa, 0xe3);
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		protected DataContractDiagramBase(DslModeling::Partition partition, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
	/// <summary>
	/// DomainClass DataContractDiagram
	/// Description for
	/// Microsoft.Practices.ServiceFactory.DataContracts.DataContractDiagram
	/// </summary>
	[global::System.CLSCompliant(true)]
			
	public partial class DataContractDiagram : DataContractDiagramBase
	{
		#region Constructors
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DataContractDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DataContractDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Microsoft.Practices.ServiceFactory.DataContracts
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollection), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollection), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractBaseCanBeContainedOnContracts), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractBaseIsBeingReferenceOnDataContractCollections), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollection)
				{
					parentElement = GetParentForDataContractCollection((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollection)childElement);
				} else
				if(childElement is global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollection)
				{
					parentElement = GetParentForPrimitiveDataTypeCollection((global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollection)childElement);
				} else
				if(childElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum)
				{
					parentElement = GetParentForDataContractEnum((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum)childElement);
				} else
				if(childElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract)
				{
					parentElement = GetParentForDataContract((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract)childElement);
				} else
				if(childElement is global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract)
				{
					parentElement = GetParentForFaultContract((global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel GetParentForFaultContract( global::Microsoft.Practices.ServiceFactory.DataContracts.Contract root )
			{
				// Segments 0 and 1
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel result = root.DataContractModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel GetParentForDataContractEnum( global::Microsoft.Practices.ServiceFactory.DataContracts.Contract root )
			{
				// Segments 0 and 1
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel result = root.DataContractModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel GetParentForDataContractCollection( global::Microsoft.Practices.ServiceFactory.DataContracts.Contract root )
			{
				// Segments 0 and 1
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel result = root.DataContractModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel GetParentForPrimitiveDataTypeCollection( global::Microsoft.Practices.ServiceFactory.DataContracts.Contract root )
			{
				// Segments 0 and 1
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel result = root.DataContractModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel GetParentForDataContract( global::Microsoft.Practices.ServiceFactory.DataContracts.Contract root )
			{
				// Segments 0 and 1
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractModel result = root.DataContractModel;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers)
				{
					global::System.Collections.IEnumerable elements = GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape), "FaultMembersCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues)
				{
					global::System.Collections.IEnumerable elements = GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape), "ValuesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers)
				{
					global::System.Collections.IEnumerable elements = GetDataContractForDataContractCompartmentShapeDataMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape), "DataMembersCompartment", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartmentFromLastLink(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers root)
			{
				// Segment 0
				global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract result = root.FaultContract;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartment(global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember root)
			{
				// Segments 1 and 0
				global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract result = root.FaultContract;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartmentFromLastLink(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues root)
			{
				// Segment 0
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum result = root.DataContractEnum;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartment(global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue root)
			{
				// Segments 1 and 0
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum result = root.DataContractEnum;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetDataContractForDataContractCompartmentShapeDataMembersCompartmentFromLastLink(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers root)
			{
				// Segment 0
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract result = root.DataContract;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetDataContractForDataContractCompartmentShapeDataMembersCompartment(global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember root)
			{
				// Segments 1 and 0
				global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract result = root.DataContract;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape), "FaultMembersCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape), "ValuesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetDataContractForDataContractCompartmentShapeDataMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape), "DataMembersCompartment", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember && e.DomainProperty.Id == global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape), "FaultMembersCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue && e.DomainProperty.Id == global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape), "ValuesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember && e.DomainProperty.Id == global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractForDataContractCompartmentShapeDataMembersCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape), "DataMembersCompartment", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape compartmentShape = pel as global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape), "FaultMembersCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape), "FaultMembersCompartment", repaintOnly);
					}
				}
				if(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape compartmentShape = pel as global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape), "ValuesCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape), "ValuesCompartment", repaintOnly);
					}
				}
				if(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetDataContractForDataContractCompartmentShapeDataMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape compartmentShape = pel as global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractForDataContractCompartmentShapeDataMembersCompartmentFromLastLink((global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape), "DataMembersCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractForDataContractCompartmentShapeDataMembersCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape), "DataMembersCompartment", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractHasDataMembers).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFaultContractForFaultContractCompartmentShapeFaultMembersCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContractCompartmentShape), "FaultMembersCompartment", repaintOnly);
					}
				}
				if(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumHasEnumNamedValues).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractEnumForDataContractEnumCompartmentShapeValuesCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.EnumNamedValue)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnumCompartmentShape), "ValuesCompartment", repaintOnly);
					}
				}
				if(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractHasDataMembers).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetDataContractForDataContractCompartmentShapeDataMembersCompartment((global::Microsoft.Practices.ServiceFactory.DataContracts.DataMember)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCompartmentShape), "DataMembersCompartment", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractBaseCanBeContainedOnContracts), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractBaseIsBeingReferenceOnDataContractCollections), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDiagram diagram = linkShape.Diagram as global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
