//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ServiceFactory.Common.Dsl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.ServiceFactory.Common.Dsl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated objects: {0}.
        /// </summary>
        internal static string GeneratedObjects {
            get {
                return ResourceManager.GetString("GeneratedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are elements with invalid ArtifactLinks. Verify that the selected Mapping Table has valid projects or is not empty..
        /// </summary>
        internal static string InvalidArtifactLinks {
            get {
                return ResourceManager.GetString("InvalidArtifactLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referred {0} Element is invalid or corrupt..
        /// </summary>
        internal static string InvalidMoniker {
            get {
                return ResourceManager.GetString("InvalidMoniker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model cannot perform validation..
        /// </summary>
        internal static string InvalidValidationController {
            get {
                return ResourceManager.GetString("InvalidValidationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;Id&apos; attribute,.
        /// </summary>
        internal static string MissingIdKey {
            get {
                return ResourceManager.GetString("MissingIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Missing Id attribute&apos; warnigns are temporary and they will be removed after saving this model file with the current version of the Web Service Software Factory 2010..
        /// </summary>
        internal static string MissingIdWarnings {
            get {
                return ResourceManager.GetString("MissingIdWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced element in &apos;{0}&apos; was not found or could not be resolved..
        /// </summary>
        internal static string ReferenceElementNotFound {
            get {
                return ResourceManager.GetString("ReferenceElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation complete: {0} errors, {1} warnings, {2} information messages.
        /// </summary>
        internal static string ValidationEndedMessage {
            get {
                return ResourceManager.GetString("ValidationEndedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating model....
        /// </summary>
        internal static string ValidationProgressMessage {
            get {
                return ResourceManager.GetString("ValidationProgressMessage", resourceCulture);
            }
        }
    }
}
