//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Microsoft.Practices.ServiceFactory.HostDesigner
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\14.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(HostDesignerExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(HostDesignerExplorerToolWindow), Constants.HostDesignerEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@Host ToolsToolboxTab;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", "Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab",
					"@HostApplicationToolboxItem;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					"Microsoft.Practices.ServiceFactory.HostDesigner.HostApplicationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"HostApplication", 
					"@HostApplicationToolboxBitmap;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab",
					"@ServiceToolboxItem;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					"Microsoft.Practices.ServiceFactory.HostDesigner.ServiceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Service", 
					"@ServiceToolboxBitmap;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab",
					"@EndpointToolboxItem;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					"Microsoft.Practices.ServiceFactory.HostDesigner.EndpointToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Endpoint", 
					"@EndpointToolboxBitmap;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab",
					"@ClientApplicationToolboxItem;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					"Microsoft.Practices.ServiceFactory.HostDesigner.ClientApplicationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClientApplication", 
					"@ClientApplicationToolboxBitmap;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab",
					"@ProxyToolboxItem;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					"Microsoft.Practices.ServiceFactory.HostDesigner.ProxyToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Proxy", 
					"@ProxyToolboxBitmap;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("Microsoft.Practices.ServiceFactory.HostDesigner.Host ToolsToolboxTab",
					"@ProxyEndpointConnectionToolToolboxItem;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					"Microsoft.Practices.ServiceFactory.HostDesigner.ProxyEndpointConnectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ProxyEndpointConnectionTool", 
					"@ProxyEndpointConnectionToolToolboxBitmap;Microsoft.Practices.ServiceFactory.HostDesigner.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideEditorFactory(typeof(HostDesignerEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(HostDesignerEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(HostDesignerEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"HostDesigner", typeof(HostDesignerEditorFactory))]

	internal abstract partial class HostDesignerPackageBase : DslShell::ModelingPackage
	{
		protected global::Microsoft.Practices.ServiceFactory.HostDesigner.HostDesignerToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new HostDesignerEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Microsoft.Practices.ServiceFactory.HostDesigner.HostDesignerToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			HostDesignerCommandSet commandSet = new HostDesignerCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			HostDesignerClipboardCommandSet clipboardCommandSet = new HostDesignerClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(HostDesignerExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Microsoft.Practices.ServiceFactory.HostDesigner
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 10)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Microsoft.Practices.ServiceFactory.HostDesigner.HostDesignerDirectiveProcessor), global::Microsoft.Practices.ServiceFactory.HostDesigner.HostDesignerDirectiveProcessor.HostDesignerDirectiveProcessorName, "A directive processor that provides access to HostDesigner files")]
	[global::System.Runtime.InteropServices.Guid(Constants.HostDesignerPackageId)]
	internal sealed partial class HostDesignerPackage : HostDesignerPackageBase
	{
	}
}
