//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Modeling.CodeGeneration.Strategies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Modeling.CodeGeneration.Strategies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model element does not implement IExtensibleObject or the extender .does not implement the ArtifactLink property..
        /// </summary>
        internal static string ArtifactLinkNotImplemented {
            get {
                return ResourceManager.GetString("ArtifactLinkNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly reference &apos;{0}&apos; could not be resolved. .
        /// </summary>
        internal static string AssemblyNotResolvedException {
            get {
                return ResourceManager.GetString("AssemblyNotResolvedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate classes because no top-level element with complex type were found for element &apos;{0}&apos;..
        /// </summary>
        internal static string CodeGenerationElementWithoutType {
            get {
                return ResourceManager.GetString("CodeGenerationElementWithoutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a template matching the target project language or template is empty..
        /// </summary>
        internal static string EmptyOrNonExistentTemplate {
            get {
                return ResourceManager.GetString("EmptyOrNonExistentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generation.
        /// </summary>
        internal static string Generation_Error_Title {
            get {
                return ResourceManager.GetString("Generation_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model element does not implement the IExtensible interface..
        /// </summary>
        internal static string IExtensibleObjectNotImplemented {
            get {
                return ResourceManager.GetString("IExtensibleObjectNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate to project due to incompatible project language..
        /// </summary>
        internal static string InvalidProjectLanguage {
            get {
                return ResourceManager.GetString("InvalidProjectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact link does not provide a TextTemplateAttribute..
        /// </summary>
        internal static string TextTemplateAttributeNotFound {
            get {
                return ResourceManager.GetString("TextTemplateAttributeNotFound", resourceCulture);
            }
        }
    }
}
